### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by vidolretia** [mochimilk/retia-project#1]
- [x] usernameと紐付くニックネーム、なければdisplay_nameを返す
- [x] いたずら防止用display_name変換
- [x] 連投防止用重複トゥーチェック
- [x] バ部は廃部
- [x] 〇〇と聞いて
- [x] 特定ワードに反応してトゥー
- [x] 定期トゥー用cron準備
- [ ] 外部ファイルからテキスト拾って定期トゥー
- [x] 自分に反応しない
- [ ] ハッシュタグに反応しない
- [x] spoiler_textがあれば反応しない
- [x] Dockerがどっか～ん？
- [x] メンションに反応してみる（LTLから見えないやつ）
- [x] メンションする（LTLから見えるやつ）
- [ ] 誕生日（アカウント作成日）を教える
- [ ] random.choiceを使って占ってみる
- [x] on_updateイベント内でmastodon.timline使わずに、on_updateから最新のトゥーを拾う
- [x] botに反応しない
- [x] 自力で再起動する
- [x] トゥートに対する返信でなければローカルタイムラインに表示されるから、その本文の先頭が「@bot名」になってるトゥー拾って、そのトゥーのin_reply_idだかに返信すればいいんでない？
- [x] 道路交通情報機能
- [ ] 道路交通情報機能の改装（500文字で分割、CW付ける、何もない場合のメッセージ）
- [x] 曜日を教えてくれる
- [ ] 今日の下着の色
- [ ] 好感度
- [ ] 今日の夕飯
- [ ] メンションかメンションじゃないか判定しつつ、返答する関数は大体同じだからまとめる
- [x] 生成したトゥート本文にNGワードがあれば投稿しない
- [ ] spoiler_textがあるトゥートはブーストしない
- [ ] 最寄りのステーキ宮を教えてくれる
- [ ] ブロッコリー警察
- [ ] 今日の早明浦
- [ ] ビール！ビール！
- [ ] 万世ポイント

**Comment by mochimilk** [comment]
〇〇と聞いて→正規表現がアレだけどまあ動く

**Comment by mochimilk** [comment]
crontab -l > ~/crontab　でバックアップ
crontab -e
これ追加↓
`0 * * * * /[PYTHON_PATH]/python3 /[HOME]/[USER]/xxxx.py > /[PATH]/cron.log 2>&1`
スクリプト内でファイル読み込ませる場合はフルパスで書く。
（cronから実行させるとcronのあるディレクトリがカレントディレクトリになる）

**Comment by mochimilk** [comment]
- usernameと紐付くニックネーム、なければdisplay_nameを返す
- いたずら防止用display_name変換

1. 外部jsonファイルを用意、{'username':'NICKNAME',...}を書く
2. jsonファイル読み込み
3. 最新トゥーのusernameを比較、該当ニックネームがあれば変換して名前を呼ぶ。
4. 該当ニックネームがなければdisplay_nameの「@」「#」「http*://」を別の文字に変換
5. 変換後のdisplay_name＋さんで名前を呼ぶ。

**Comment by mochimilk** [comment]
- メンションに反応してみる
StreamListener.on_notification(notification)でNotification dictsを拾う⇒'type'がmentionの場合、accountからidを拾う⇒Mastodon.status_post(status, in_reply_to_id=ID　で反応できるかも？

[http://mastodonpy.readthedocs.io/en/stable/#streaming](http://mastodonpy.readthedocs.io/en/stable/#streaming)

**Comment by mochimilk** [comment]
- 自力で再起動する
heart beat⇒keep-alive？
heart beatが無い⇒停止してる⇒自力で起動？

**Comment by mochimilk** [comment]
- on_updateイベント内でmastodon.timline使わずに、on_updateから最新のトゥーを拾う
tl = [status] で最新のトゥートをdict形式で拾えるはずなのにリスト型にしないとなぜかエラー。
でも動くからとりあえずOK。

**Comment by mochimilk** [comment]
- botに反応しない関数
bot_namesを外部ファイルとかにするとすっきりするかもしれんけど速度重視
これが速いか知らんけど

```
def is_bot(app):
    if not app: return False
    bot_names = [
        'オフ会カレンダー',
        'off_bot',
        '安価bot',
        '不適切bot',
        "D's toot trends App",
        'nekonyanApp',
        '色bot',
        'ダイスbot',
        'VRれてぃあ'
    ]
    return app['name'] in bot_names

```

**Comment by mochimilk** [comment]
- on_updateイベントでのタイムライン取得
status[‘XXXX’]で中身取れるやんけ！

**Comment by mochimilk** [comment]
- メンションする
ローカルタイムラインで見えるもの：トゥーの先頭にbotへのメンションがあればトゥートのstatus[‘id’]を取得→status_post(status=‘@‘+status[‘account’][‘username’]+’ ‘+トゥー内容, in_reply_to_id=メンションしたいトゥートのid) 
でメンションになる。usernameの前に@付け忘れると通知してくれない。
ていうかusername無しでもちゃんとメンションのスレッドとして機能する

**Comment by mochimilk** [comment]
- spoiler_textがあれば反応しない
```
if status['spoiler_text'] != '':
            my_next_toot = ''
```
トゥー生成部分にこれ入れればたぶんいける

**Comment by mochimilk** [comment]
- 何曜日か教えてくれる

 ```
youbi = ["月","火","水","木","金","土","日"]
nowyobi = datetime.date.today()
random.seed(nowyobi.weekday())
y = random.randint(0,6)
youbi[y] 
```
これで曜日の取得可能

**Comment by mochimilk** [comment]
- 道路交通情報
trafic.pyを読み込ませてトゥーするところまでは成功

**Comment by mochimilk** [comment]
- 生成したトゥート本文にNGワードがあれば投稿しない
暫定的にNGワードを「（自主規制）」に置き換えて投稿

**Comment by mochimilk** [comment]
- 自力で再起動する
cronで1時間ごとに再起動する力業で暫定対応
